name: 'Deploy'
description: 'Create deployments and services'
inputs:
  application:
    description: 'Application for which docker image should be build'
    required: true
  docker_image_tag: 
    description: 'Tag how image should be tagged'
    required: true
  type:
    description: 'dev or prd'
    required: true
runs:
  using: "composite"
  steps:
    - name: Create deployment
      run: kubectl apply-f k8s/${{inputs.application}}/${{inputs.type}}/deployment.yaml
      shell: cmd
    - name: Create service
      run: kubectl apply -f k8s/${{inputs.application}}/${{inputs.type}}/service.yaml
      shell: cmd
