name: Node mock app pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - node-mock-app/api-spec.yaml
jobs:
  build:
    name: Build new node-mock-app image
    runs-on: self-hosted
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - run: echo Building new node-mock-app image
    - name: Build image
      uses: ./.github/actions/build
      with:
          application: node-mock-app
          docker_image_tag: eduardsevele/node-mock-app:${{github.sha}}
    - if success:
      run: ./send_notification.sh "Build node mock image" 0
      shell: pwsh
    - if failure:
      run: ./send_notification.sh "Build node mock image" 1
      shell: pwsh
  deploy-dev:
    name: Deploy dev version of node-mock-app
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - run: echo Deploying node-mock-app-dev
      - name: Deploy dev
        uses: ./.github/actions/deploy
        with:
            application: node-mock-app
            docker_image_tag: eduardsevele/node-mock-app:${{github.sha}}
            type: dev
      - if success:
        run: ./send_notification.sh "Deploy dev version of node mock app" 0
        shell: pwsh
      - if failure:
        run: ./send_notification.sh "Deploy dev version of node mock app" 1
        shell: pwsh
  test-dev:
    name: Start tests for dev
    runs-on: self-hosted
    needs: [deploy-dev]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - run: echo Performing tests for dev enironment
      - name: Start api-tests-dev
        uses: ./.github/actions/deploy
        with:
            application: api-tests
            docker_image_tag: eduardsevele/api-tests:latest
            type: dev
      - if success:
        run: ./send_notification.sh "Run tests for node mock dev" 0
        shell: pwsh
      - if failure:
        run: ./send_notification.sh "Run tests for node mock dev" 1
        shell: pwsh
  deploy-prd:
    name: Deploy prd version of node-mock-app
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - run: echo Deploying node-mock-app-prd
      - name: Deploy prd
        uses: ./.github/actions/deploy
        with:
            application: node-mock-app
            docker_image_tag: eduardsevele/node-mock-app:latest
            type: prd
      - if success:
        run: ./send_notification.sh "Deploy prd version of node mock app" 0
        shell: pwsh
      - if failure:
        run: ./send_notification.sh "Deploy prd version of node mock app" 0
        shell: pwsh
  test-prd:
    name: Start tests for prd
    runs-on: self-hosted
    needs: [deploy-prd]
    steps:
      - run: echo Performing tests for prd environment
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Start api-tests-dev
        uses: ./.github/actions/deploy
        with:
            application: api-tests
            docker_image_tag: eduardsevele/api-tests:latest
            type: prd
      - if success:
        run: ./send_notification.sh "Run tests for node mock prd" 0
        shell: pwsh
      - if failure:
        run: ./send_notification.sh "Run tests for node mock prd" 1
        shell: pwsh
        
  
