name: Node mock app pipeline image replace
on:
  workflow_dispatch:
jobs:
  build:
    name: Build new node-mock-app image
    runs-on: self-hosted
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - run: echo Building new node-mock-app image
    - name: Build image
      uses: ./.github/actions/build
      with:
          application: node-mock-app
          docker_image_tag: eduardsevele/node-mock-app:${{github.sha}}
  deploy-dev:
    name: Update image for node-mock-app-dev
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - run: kubectl set image deployment/api-tests-dev-deployment api-tests-dev=eduardsevele/node-mock-app:${{github.sha}}
      - run: kubectl rollout restart deployment api-tests-dev-deployment
  test-dev:
    name: Start tests for dev
    runs-on: self-hosted
    needs: [deploy-dev]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - run: echo Deploying node-mock-app-dev
      - name: Start api-tests-dev
        uses: ./.github/actions/deploy
        with:
            application: api-tests
            docker_image_tag: eduardsevele/api-tests:latest
            type: dev
  deploy-prd:
    name: Update image for node-mock-app-prd
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - run: kubectl set image deployment/api-tests-prd-deployment api-tests-prd=eduardsevele/node-mock-app:${{github.sha}}
      - run: kubectl rollout restart deployment api-tests-prd-deployment
  test-prd:
    name: Start tests for prd
    runs-on: self-hosted
    needs: [deploy-prd]
    steps:
      - run: echo Deploying node-mock-app-dev
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Start api-tests-dev
        uses: ./.github/actions/deploy
        with:
            application: api-tests
            docker_image_tag: eduardsevele/api-tests:latest
            type: prd
        
  
